[package]
name = "c2"
version = "0.0.1"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
axum = { version = "0.6.20", features = ["headers", "macros"] }
axum-extra = "0.8.0"
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
serde_with = "3.4.0"
tokio = { version = "1.34.0", features = ["full"] }
sqlx = { version = "0.7.2", features = ["postgres", "runtime-tokio"] }
minijinja = { version = "1.0.10", features = ["loader"] }
oauth2 = "4.4.2"
uuid = { version = "1.5.0", features = ["v4"] }
reqwest = "0.11.22"
dotenvy = "0.15.7"
constant_time_eq = "0.3.0"
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.4.4", features = ["fs", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
